name: C++ CI

on:
  push:
  pull_request:

jobs:
  build-test:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -DRWN_BUILD_TESTS=ON
      - name: Build
        run: cmake --build build --config Debug
      - name: Workflow unit and security tests
        run: ctest --test-dir build -C Debug --output-on-failure
